/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author andrelima
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroFuncionario = new javax.swing.JMenuItem();
        cadastroOrdemServico = new javax.swing.JMenuItem();
        cadastroProduto = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        realizarVenda = new javax.swing.JMenuItem();
        listarVendas = new javax.swing.JMenuItem();
        menuServico = new javax.swing.JMenu();
        cadastroOrdem = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        sobreAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordem de Serviço");

        menuCadastro.setText("Cadastro");

        cadastroCliente.setText("Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroCliente);

        cadastroFuncionario.setText("Funcionario");
        cadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroFuncionario);

        cadastroOrdemServico.setText("Serviço");
        cadastroOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroOrdemServicoActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroOrdemServico);

        cadastroProduto.setText("Produto");
        cadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroProduto);

        barraMenu.add(menuCadastro);

        menuVenda.setText("Venda");
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });

        realizarVenda.setText("Realizar Venda");
        realizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVendaActionPerformed(evt);
            }
        });
        menuVenda.add(realizarVenda);

        listarVendas.setText("Listar Vendas");
        listarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasActionPerformed(evt);
            }
        });
        menuVenda.add(listarVendas);

        barraMenu.add(menuVenda);

        menuServico.setText("Ordem de Serviço");
        menuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServicoActionPerformed(evt);
            }
        });

        cadastroOrdem.setText("Cadastrar Ordem");
        cadastroOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroOrdemActionPerformed(evt);
            }
        });
        menuServico.add(cadastroOrdem);

        barraMenu.add(menuServico);

        menuSobre.setText("Sobre");

        sobreAjuda.setText("Ajuda");
        sobreAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreAjudaActionPerformed(evt);
            }
        });
        menuSobre.add(sobreAjuda);

        barraMenu.add(menuSobre);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sobreAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreAjudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sistema de Ordem de serviço\nVersão 1.0\nDireitos Reservados");
                
    }//GEN-LAST:event_sobreAjudaActionPerformed

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        // TODO add your handling code here:
        FormCliente form = new FormCliente(this, true); //instaciar formCliente, this chama a partir desse formulario, true é uma janela modal, sobrepondo o principal.
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // não deixa fechar pelo X da janela, apenas pelo botão fechar
        form.setLocationRelativeTo(null);
        form.setResizable(false); // tira botaão maximizar
        form.setVisible(true); // mostra a janela
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void cadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroFuncionarioActionPerformed
        // TODO add your handling code here:
        FormFuncionario form = new FormFuncionario(this, true); //instaciar formCliente, this chama a partir desse formulario, true é uma janela modal, sobrepondo o principal.
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // não deixa fechar pelo X da janela, apenas pelo botão fechar
        form.setLocationRelativeTo(null);
        form.setResizable(false); // tira botaão maximizar
        form.setVisible(true); 
    }//GEN-LAST:event_cadastroFuncionarioActionPerformed

    private void cadastroOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroOrdemServicoActionPerformed
        // TODO add your handling code here:
        FormServico form = new FormServico(this, true); //instaciar formCliente, this chama a partir desse formulario, true é uma janela modal, sobrepondo o principal.
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // não deixa fechar pelo X da janela, apenas pelo botão fechar
        form.setLocationRelativeTo(null);
        form.setResizable(false); // tira botaão maximizar
        form.setVisible(true); 
    }//GEN-LAST:event_cadastroOrdemServicoActionPerformed

    private void cadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProdutoActionPerformed
        // TODO add your handling code here:
        FormProduto form = new FormProduto(this, true); //instaciar formCliente, this chama a partir desse formulario, true é uma janela modal, sobrepondo o principal.
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // não deixa fechar pelo X da janela, apenas pelo botão fechar
        form.setLocationRelativeTo(null);
        form.setResizable(false); // tira botaão maximizar
        form.setVisible(true); 
    }//GEN-LAST:event_cadastroProdutoActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_menuVendaActionPerformed

    private void menuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuServicoActionPerformed

    private void realizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVendaActionPerformed
        // TODO add your handling code here:
        FormVenda form = new FormVenda(this,true);
       // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_realizarVendaActionPerformed

    private void cadastroOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroOrdemActionPerformed
        // TODO add your handling code here:
        FormOrdemServico form = new FormOrdemServico(this,true);
       // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);                            
    }//GEN-LAST:event_cadastroOrdemActionPerformed

    private void listarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasActionPerformed
        // TODO add your handling code here:
        FormListaVendas form = new FormListaVendas(this,true);
       // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_listarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new FormPrincipal().setVisible(true);
                FormPrincipal form = new FormPrincipal();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroFuncionario;
    private javax.swing.JMenuItem cadastroOrdem;
    private javax.swing.JMenuItem cadastroOrdemServico;
    private javax.swing.JMenuItem cadastroProduto;
    private javax.swing.JMenuItem listarVendas;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuServico;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JMenuItem realizarVenda;
    private javax.swing.JMenuItem sobreAjuda;
    // End of variables declaration//GEN-END:variables
}
